development:
  adapter: postgresql
  encoding: unicode
  database: maintenance_log_dev
  pool: 2
  username: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: production
  url: <%= ENV[‘DATABASE_URL’] %>
  pool: 5
