default: &default
  adapter: postgresql
  encoding: unicode

local: &local
  pool: 2
  username: postgres

development:
  <<: *default
  <<: *local
  database: maintenance_log_dev

test:
  <<: *default
  <<: *local
  database: maintenance_log_test

production:
  <<: *default
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>